* Elements Concepts:
** 对象
   属性 方法 事件

   对象代表应用程序的元素，集合是一个包含多个其他对象的对象
   方法是对象可以执行的操作
   属性是对象的特征
   事件是由对象识别的操作，事件可作为用户操作或程序代码的结果发生

Range
表示一个单元格、一行、一列、一个包含单个或若干连续单元格区域的选定单元格范围，或者一个三维区域。

Worksheet
指定工作簿或活动工作簿中所有 Worksheet 对象的集合。 每个 Worksheet 对象都代表一个工作表

Application
代表整个Microsoft Excel应用程序

Workbook
代表一个 Microsoft Excel 工作簿。

ODBCConnection 对象 (Excel)
代表 ODBC 连接

    ODBC 连接可存储在 Excel 工作簿中。 当Excel工作簿时，它会创建 ODBC 连接的内存副本，称为 ODBCConnection 对象。

    ODBCConnection 对象包含与连接有关的信息，例如要连接到的服务器的名称以及要在服务器上打开的对象的名称。 （可选）ODBCConnection 对象也可以包括身份验证凭据信息或要传递到服务器并执行的命令（例如，要由 SQL Server 执行的 SELECT 语句）。
    
** VBA参考
   项目：一组模块
   模块：一组声明，后跟过程
   过程：A named sequence of statements executed as a unit
        Function Property Sub
   
   声明语句：使用声明语句命名和定义过程、变量、数组和常量。 在声明过程、变量或常量时，您还将根据您放置声明的位置和用于声明它的关键字来定义其范围

   可执行语句：可执行语句可启动操作。 它可以执行一个方法或函数，还可以在代码块中进行循环或分支。 可执行语句通常包含数学或条件运算符

   赋值语句：赋值语句将值或表达式分配给变量或常量。 赋值语句始终包括等号 () =

   Sub过程：执行但不返回值，可以调用返回值ev
   Function过程：类似Sub，但可以返回值
   备注：'  or  Rem 
    
'''
  Sub ApplyFormat() 
    Const limit As Integer = 33 
    Dim myCell As Range 
    ' More statements 
  End Sub
'''
sub声明一个名为ApplyFormat的过程，调用或运行该过程，就会执行里面的所有语句
Dim声明变量
Const指定limit的数据类型和值

** 常用函数
   Debug.Print
       Dim MyVar
       MyVar = "Come see me in the Immediate pane."
       Debug.Print MyVar
   MsgBox ("hello 123")



XlSheetType枚举

   | 名称                   |    值 | 说明                   |
   | xlChart                | -4109 | 图表                   |
   | xlDialogSheet          | -4116 | 对话框工作表           |
   | xlExcel4IntlMacroSheet |     4 | Excel版本4国际宏工作表 |
   | xlExcel4MacroSheet     |     3 | Excel版本4宏工作表     |
   | xlWorksheet            | -4167 | 工作表                 |
* 实际问题
** 从活动Excel工作簿提取元数据   
** 遍历所有工作表
* 学习过程
  type属性找半天没找到，最后是跟踪变量发现的
  workbook.saveas方法出问题了，现实和书上的不符
* Reference
 https://docs.microsoft.com/zh-cn/office/vba/api/overview/language-reference 
  
